<a href="https://colab.research.google.com/github/Nishant6397/TenserFlow-fundamentals/blob/main/Tenserflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we are going to explore the  some of the most fundamental concepts of Tenserflow

*More Specifically we are cover:

*Intro to Tensors

*Getting information from tensors

*Manipulating the tensors

*Tensors & numpy

*Using @tf.function(a way to speed up your regular python functions)

*Using GPUs with Tensorflow or TPUs

*Exercises to try for yourself


In [ ]:
# Import Tensorflow
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.15.0


In [ ]:
# Create a tensor with tf.constant
# Creates a constant tensor from a tensor-like object.
# Link for more understanding
# https://www.tensorflow.org/api_docs/python/tf/constant
scalar = tf.constant(7)
scalar

# Constant 1-D Tensor from a python list.
b= tf.constant([1, 2, 3, 4, 5, 6])
b

# Or a numpy array
a = np.array([[1, 2, 3], [4, 5, 6]])
tf.constant(a)
a






array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimenstions for that
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7], [10,9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create a another matrix
another_matrix = tf.constant([[10.,8,],[3.,5.], [3.,7.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 3.,  5.],
       [ 3.,  7.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
one_more_matrix = tf.constant([[[2,3],[4,5]]])
one_more_matrix

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

In [ ]:
one_more_matrix.ndim

3

In [ ]:
#Lets create a tensor
tensor = tf.constant([[[[1,2,3], [4,4,5]], [[2,3,2],[3,4,5]],[[3,2,4], [3,4,5]]]])
tensor



<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 4, 5]],

        [[2, 3, 2],
         [3, 4, 5]],

        [[3, 2, 4],
         [3, 4, 5]]]], dtype=int32)>

In [ ]:
tensor.ndim

4

#What we've created so far:
*Scalar: a single number

*Vector: a number with direction (e.g. wind speed and direction)

*Matrix: a 2-dimensional array of numbers

*Tensor: an n-dimensional array of numbers (where n can be any number , a-0 dimensional , a 1 dimension is a vector)

### Creating Tensor with tf.variable

https://www.tensorflow.org/api_docs/python/tf/Variable

Why would we use variable over constant tensors


In variable tensors we can change the value of existing tensor with the help of assign function

In [ ]:
#Create a above tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

#but for constant we can't do this so we have to decide what we use variable or constant


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors
IN the starting we initailize with random wieghts and biases in the beginning then we train our model with the help of back propagation algorithm it will tweaks our weights and biases in this manner our neural network train
so for the we want random tensor
So here is a function in Tensorflow for creating the random tensors


https://www.tensorflow.org/api_docs/python/tf/random/uniform

In [ ]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1= random_1.uniform(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle th order of elements
https://www.tensorflow.org/api_docs/python/tf/random/shuffle

In [ ]:
#Shuffke a tensor (shuffle the data wanted to inherit the data but does not affect the learning)
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim ,  not_shuffled


(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

In [ ]:
shiffled  = tf.random.shuffle(
    not_shuffled
)
shiffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

SET Seed

It looks like if we want our shuffled tensors to be in the same order we've go to use global level random seed as well as operation level random seed:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [ ]:
tf.random.set_seed(42) #global level random seed
# tf.random.set_seed(
#     seed
# )
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

 # Other ways to create tensors

In [ ]:
# Create a tensors all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensors of all zeroes
tf.zeros(shape= ( 3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tensors

The main difference between NUmpy arrays and tenserflow is that tensors can be run on a GPU Computing

In [ ]:
#Youcan aksi tyrb Numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) #create a Numpy array between 1 and 25
numpy_A

#X = tf.constant(some_matrix) #capital for matrix or tensor
#y = tf.constant(vector) non capital for vecot

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [36]:
# We can directly pass the  numpy array into the Tenserflow  toi made a tensor
A = tf.constant(numpy_A, shape= (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>